name: Go Modernize Check

on:
  push:

jobs:
  modernize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Run modernize tool
        id: run_modernize
        run: |
          # Run modernize with diff mode to see potential changes
          # 標準出力と標準エラー出力の両方をキャプチャ
          go tool modernize -test -diff ./... > modernize_output.txt 2>&1 || true
          
          # 内容を表示してデバッグ
          echo "===== modernize output ====="
          cat modernize_output.txt
          echo "===== end of output ====="

      - name: Check for differences
        id: check_diff
        run: |
          # grepを使って差分があるかどうかをチェック
          if grep -q "^-" modernize_output.txt || grep -q "^+" modernize_output.txt; then
            echo "modernize found differences"
            echo "HAS_DIFF=true" >> $GITHUB_OUTPUT
          else
            echo "No differences found in grep check"
            echo "HAS_DIFF=false" >> $GITHUB_OUTPUT
          fi
          
          # デバッグ用にファイルサイズも確認
          echo "File size: $(wc -c < modernize_output.txt) bytes"
          echo "File content preview:"
          head -n 20 modernize_output.txt

      - name: Generate summary
        if: steps.check_diff.outputs.HAS_DIFF == 'true'
        run: |
          echo "## Go Modernize Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "modernizeツールが以下の改善点を検出しました。コードをより最新のGo機能を活用するように更新することを検討してください。" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```diff' >> $GITHUB_STEP_SUMMARY
          cat modernize_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "変更を適用するには以下のコマンドを実行してください：" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "go tool modernize -test -fix ./..." >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY 